### ISSUE TITLE
Adding additional firefox colorways

### ISSUE THREAD

**Issue by awarmwildfire** [amad3v/ff-colorways#1]
Hello there, I just want to say firstly thank you so much for this project! Thanks to your help, I was able to restore the old colorways I missed. I saw that this project had colorways I didn't see before, but entering them into the firefox config section worked well. I was able to extrapolate from the colorways presented, and bring back the colorways that I was familiar with. I'll add them here:

`"abstract-bold-colorway@mozilla.org"

"abstract-balanced-colorway@mozilla.org", 
"abstract-soft-colorway@mozilla.org", 
"cheers-bold-colorway@mozilla.org", 
"cheers-balanced-colorway@mozilla.org", 
"cheers-soft-colorway@mozilla.org", 
"elemental-bold-colorway@mozilla.org", 
"elemental-balanced-colorway@mozilla.org", 
"elemental-soft-colorway@mozilla.org", 
"foto-bold-colorway@mozilla.org", 
"foto-soft-colorway@mozilla.org", 
"foto-balanced-colorway@mozilla.org", 
"graffiti-soft-colorway@mozilla.org", 
"graffiti-balanced-colorway@mozilla.org", 
"graffiti-bold-colorway@mozilla.org", 
"lush-soft-colorway@mozilla.org", 
"lush-bold-colorway@mozilla.org", 
"lush-balanced-colorway@mozilla.org"
`

I'm not sure if there are any colorways that I'm missing, but those are the ones that I remember. I hope these help!

**Comment by amad3v** [comment]
Thanks @awarmwildfire, I'm glad you found it helpful.
I updated the [README](https://github.com/amad3v/ff-colorways/blob/main/README.md) file to reflect your themes.

**Comment by awarmwildfire** [comment]
Thank you! 😄
